# Generated by Django 3.1.8 on 2021-06-09 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=1, unique=True)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=4, unique=True)),
                ('office', models.CharField(max_length=2)),
                ('name', models.CharField(max_length=20)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='section', to='core.area')),
            ],
        ),
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=8, unique=True)),
                ('cx', models.DecimalField(decimal_places=6, max_digits=9)),
                ('cy', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lx', models.DecimalField(decimal_places=6, max_digits=9)),
                ('ly', models.DecimalField(decimal_places=6, max_digits=9)),
                ('rx', models.DecimalField(decimal_places=6, max_digits=9)),
                ('ry', models.DecimalField(decimal_places=6, max_digits=9)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='land', to='core.section')),
            ],
        ),
        migrations.AddField(
            model_name='area',
            name='county',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='area', to='core.county'),
        ),
    ]
