# Generated by Django 3.1.8 on 2021-06-17 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='land',
            name='sn',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterUniqueTogether(
            name='land',
            unique_together={('sn', 'section')},
        ),
    ]
