# Generated by Django 3.1.8 on 2021-05-25 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starttime', models.DateField()),
                ('endtime', models.DateField(blank=True)),
                ('addtime', models.DateTimeField(auto_now_add=True)),
                ('updatetime', models.DateTimeField(auto_now=True)),
                ('remark', models.CharField(blank=True, max_length=200, null=True)),
                ('isvalid', models.BooleanField(default=True)),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qc_category_editor', related_query_name='qc_categoryeditor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CategorySelectName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addtime', models.DateTimeField(auto_now_add=True)),
                ('updatetime', models.DateTimeField(auto_now=True)),
                ('remark', models.CharField(blank=True, max_length=200, null=True)),
                ('isvalid', models.BooleanField(default=True)),
                ('cmpname', models.CharField(max_length=50)),
                ('cmpsn', models.CharField(max_length=10)),
                ('cmptel', models.CharField(max_length=20)),
                ('cmpfax', models.CharField(blank=True, max_length=20, null=True)),
                ('cmpaddr', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addtime', models.DateTimeField(auto_now_add=True)),
                ('updatetime', models.DateTimeField(auto_now=True)),
                ('remark', models.CharField(blank=True, max_length=200, null=True)),
                ('isvalid', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=20)),
                ('telprim', models.CharField(max_length=20)),
                ('telscnd', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('comp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contcomp', to='qc.company')),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qc_contact_rltd', related_query_name='qc_contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuestionCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SubCateSelect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TimingSelect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WorkList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starttime', models.DateField()),
                ('endtime', models.DateField(blank=True)),
                ('addtime', models.DateTimeField(auto_now_add=True)),
                ('updatetime', models.DateTimeField(auto_now=True)),
                ('remark', models.CharField(blank=True, max_length=200, null=True)),
                ('isvalid', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200)),
                ('cate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='qc.category')),
                ('contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='qc.contact')),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qc_worklist_editor', related_query_name='qc_worklisteditor', to=settings.AUTH_USER_MODEL)),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qc_worklist_spnsr', related_query_name='qc_worklistspnsr', to=settings.AUTH_USER_MODEL)),
                ('subcate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='qc.subcateselect')),
                ('timing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='qc.timingselect')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addtime', models.DateTimeField(auto_now_add=True)),
                ('updatetime', models.DateTimeField(auto_now=True)),
                ('isvalid', models.BooleanField(default=True)),
                ('ordering', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('abstract', models.CharField(blank=True, max_length=200, null=True)),
                ('rank', models.IntegerField()),
                ('type', models.IntegerField(choices=[(0, '單選題'), (1, '複選題'), (2, '填空題'), (3, '圖片題'), (4, '檔案題')], default=0)),
                ('is_required', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qc_question_cate', to='qc.questioncategory')),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qc_question_editor', to=settings.AUTH_USER_MODEL)),
                ('worklist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qc_question_worklist', to='qc.worklist')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starttime', models.DateField()),
                ('endtime', models.DateField(blank=True)),
                ('addtime', models.DateTimeField(auto_now_add=True)),
                ('updatetime', models.DateTimeField(auto_now=True)),
                ('remark', models.CharField(blank=True, max_length=200, null=True)),
                ('isvalid', models.BooleanField(default=True)),
                ('sn', models.CharField(max_length=4, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('loc_county', models.CharField(max_length=20)),
                ('loc_area', models.CharField(max_length=20)),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qc_project_editor', related_query_name='qc_projecteditor', to=settings.AUTH_USER_MODEL)),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qc_project_spnsr', related_query_name='qc_projectspnsr', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='company',
            name='cmpsponsor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cmpsponsor', to='qc.contact'),
        ),
        migrations.AddField(
            model_name='company',
            name='editor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qc_company_rltd', related_query_name='qc_companys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=100)),
                ('multi', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='q_choice', to='qc.question')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='qc.categoryselectname'),
        ),
        migrations.AddField(
            model_name='category',
            name='proj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='qc.project'),
        ),
        migrations.AddField(
            model_name='category',
            name='sponsor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qc_category_spnsr', related_query_name='qc_categoryspnsr', to=settings.AUTH_USER_MODEL),
        ),
    ]
