# Generated by Django 3.1.8 on 2021-05-25 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sched_time', models.DateField()),
                ('cmplt_time', models.DateField()),
                ('count', models.IntegerField()),
                ('isvalid', models.BooleanField(default=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('is_check', models.BooleanField(default=False)),
                ('addtime', models.DateTimeField(auto_now_add=True)),
                ('updatetime', models.DateTimeField(auto_now=True)),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to=settings.AUTH_USER_MODEL)),
                ('worklist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='qc.worklist')),
            ],
        ),
    ]
