# Generated by Django 3.1.8 on 2021-05-26 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0003_add_task_editor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='is_completed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
