# Generated by Django 3.1.8 on 2021-05-26 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0004_change_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='cmplt_time',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
