# Generated by Django 3.1.8 on 2021-05-27 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qc', '0005_change_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnsSingle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addtime', models.DateTimeField(auto_now_add=True)),
                ('updatetime', models.DateTimeField(auto_now=True)),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='single_choice', to='qc.choice')),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answer', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='single_choice_question', to='qc.question')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='anstask', to='qc.task')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
