# Generated by Django 3.1.8 on 2021-06-02 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0006_add_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='endtime',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='endtime',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='worklist',
            name='endtime',
            field=models.DateField(blank=True, null=True),
        ),
    ]
