# Generated by Django 3.1.8 on 2021-06-02 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0007_change_endtime_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcateselect',
            name='cate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='qc.category'),
            preserve_default=False,
        ),
    ]
