# Generated by Django 3.1.8 on 2021-06-02 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0008_add_cate_subcate_rlt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcateselect',
            name='cate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='qc.categoryselectname'),
        ),
    ]
