# Generated by Django 3.1.8 on 2021-06-03 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0009_change_subcate_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worklist',
            name='timing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='qc.timingselect'),
        ),
    ]
