# Generated by Django 3.1.8 on 2021-06-03 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0011_add_Qcate_subcate_rlt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='ordering',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('id', 'ordering')},
        ),
    ]
