# Generated by Django 3.1.8 on 2021-06-03 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0012_chg_order_uni'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='badimg',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/selfcheck/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='question',
            name='goodimg',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/selfcheck/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='question',
            name='method',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
