# Generated by Django 3.1.8 on 2021-06-03 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0013_add_field_of_Quest'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='improvement',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
