# Generated by Django 3.1.8 on 2021-06-03 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0014_add_quest_improve'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_filled',
            field=models.BooleanField(default=False),
        ),
    ]
