# Generated by Django 3.1.8 on 2021-06-04 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qc', '0015_add_filled_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anssingle',
            name='editor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qc_anssingle_editor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='anssingle',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qc_anssingle_task', to='qc.task'),
        ),
        migrations.CreateModel(
            name='AnsFilled',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addtime', models.DateTimeField(auto_now_add=True)),
                ('updatetime', models.DateTimeField(auto_now=True)),
                ('ans', models.CharField(max_length=50)),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qc_ansfilled_editor', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='filled_ans', to='qc.question')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qc_ansfilled_task', to='qc.task')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
