# Generated by Django 3.1.8 on 2021-06-21 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0016_add_filled_ans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='loc_area',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='loc_county',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
