# Generated by Django 3.1.8 on 2021-06-21 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_chg_sec_uq_field'),
        ('qc', '0017_chg_loc_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='loc_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.area'),
        ),
        migrations.AlterField(
            model_name='project',
            name='loc_county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.county'),
        ),
    ]
