# Generated by Django 3.1.8 on 2021-06-21 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_chg_sec_uq_field'),
        ('qc', '0018_chg_locfield_toFK'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='land',
            field=models.ManyToManyField(to='core.Land'),
        ),
    ]
