# Generated by Django 3.1.8 on 2021-05-03 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('psn', models.CharField(max_length=4)),
                ('pname', models.CharField(max_length=20)),
                ('ploc_county', models.CharField(max_length=20)),
                ('ploc_area', models.CharField(max_length=20)),
                ('ploc_secnum_list', models.CharField(blank=True, max_length=20, null=True)),
                ('pstatrtime', models.DateField()),
                ('pendtime', models.DateField(blank=True, null=True)),
                ('paddtime', models.DateTimeField(auto_now_add=True)),
                ('pupdatetime', models.DateTimeField(auto_now=True)),
                ('peditor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proj_editor', to=settings.AUTH_USER_MODEL)),
                ('psponsor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proj_sponsor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
