# Generated by Django 3.1.8 on 2021-05-03 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qcmanager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csn', models.CharField(max_length=4)),
                ('cname', models.CharField(max_length=100)),
                ('cstatrtime', models.DateField()),
                ('cendtime', models.DateField(blank=True, null=True)),
                ('caddtime', models.DateTimeField(auto_now_add=True)),
                ('cupdatetime', models.DateTimeField(auto_now=True)),
                ('ceditor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cate_editor', to=settings.AUTH_USER_MODEL)),
                ('cproj', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cate_proj', to='qcmanager.project')),
                ('csponsor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cate_sponsor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
