# Generated by Django 3.1.8 on 2021-05-03 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qcmanager', '0002_add_ProjCategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmpname', models.CharField(max_length=50)),
                ('cmpsn', models.CharField(max_length=8, unique=True)),
                ('cmpsponsor', models.CharField(max_length=20)),
                ('cmptel', models.CharField(max_length=20)),
                ('cmpfax', models.CharField(blank=True, max_length=20, null=True)),
                ('cmpaddr', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cntname', models.CharField(max_length=20)),
                ('cnttel', models.CharField(max_length=20)),
                ('cntemail', models.EmailField(max_length=254)),
                ('cntcomp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cnt_comp', to='qcmanager.company')),
            ],
        ),
    ]
