# Generated by Django 3.1.8 on 2021-05-07 01:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qcmanager', '0005_add_subcate'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimingChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SlfChkStandIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chkloc', models.CharField(max_length=100)),
                ('chktime', models.DateField()),
                ('addtime', models.DateTimeField(auto_now_add=True)),
                ('edittime', models.DateTimeField(auto_now=True)),
                ('sn', models.CharField(max_length=20)),
                ('worksn', models.CharField(max_length=20)),
                ('amount', models.IntegerField()),
                ('stncrtf', models.BooleanField()),
                ('stncrtf_rk', models.IntegerField(choices=[(1, 'Normal'), (2, 'Medium'), (3, 'High')])),
                ('stnoutfit', models.BooleanField()),
                ('stnoutfit_rk', models.IntegerField(choices=[(1, 'Normal'), (2, 'Medium'), (3, 'High')])),
                ('stnrust', models.BooleanField()),
                ('stnrust_rk', models.IntegerField(choices=[(1, 'Normal'), (2, 'Medium'), (3, 'High')])),
                ('prlnrust', models.BooleanField()),
                ('prlnrust_rk', models.IntegerField(choices=[(1, 'Normal'), (2, 'Medium'), (3, 'High')])),
                ('prlndfm', models.BooleanField()),
                ('prlndfm_rk', models.IntegerField(choices=[(1, 'Normal'), (2, 'Medium'), (3, 'High')])),
                ('chkuser', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qcmanager_slfchkstandin_chkuser', to=settings.AUTH_USER_MODEL)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='qcmanager.contact')),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qcmanager_slfchkstandin_editor', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='qcmanager.project')),
                ('timing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='qcmanager.timingchoice')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
