# Generated by Django 3.1.8 on 2021-05-05 03:28

from django.db import migrations, models
import django.db.models.deletion
import qcmanager.models


class Migration(migrations.Migration):

    dependencies = [
        ('qcmanager', '0005_add_subcate'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelfCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sccate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sc_cate', to='qcmanager.projcategory')),
                ('scsubcate', models.ForeignKey(limit_choices_to=qcmanager.models.SelfCheck.limit_choice_of_subcat, on_delete=django.db.models.deletion.PROTECT, related_name='sc_subcate', to='qcmanager.subcateselect')),
            ],
        ),
    ]
